#pragma once
#include "3-longest-substring-without-repeating.h"
#include "15-3sum.h"
#include "16-3sum-closest.h"
#include "56-merge-intervals.h"
#include "66-plus-one.h"
#include "116-populating-next-right.h"
#include "172-factorial-trailing-zeroes.h"
#include "263-ugly-number.h"
#include "264-ugly-number-2.h"
#include "278-first-bad-version.h"
#include "297-serialize-and-deserialize-binary-tree.h"
#include "313-super-ugly-number.h"
#include "371-sum-of-two-integers.h"
#include "382-linked-list-random-node.h"
#include "509-fibonacci-number.h"
#include "560-subarray-sum-equals-k.h"
#include "709-to-lower-case.h"
#include "763-partition-labels.h"
#include "819-most-common-word.h"
#include "833-find-and-replace-in-string.h"
#include "836-rectangle-overlap.h"
#include "905-sory-array-by-parity.h"
#include "941-valid-mountain-array.h"
#include "1010-pair-of-songs-divisible-by-60.h"
#include "1146-snapshot-array.h"
#include "1275-find-winner-tic-tac-toe.h"
#include "1344-angle-between-hands-of-clock.h"
#include "1352-product-of-the-last-k-numbers.h"
#include "1544-make-the-string-great.h"

#define ENUMERATE_PROBLEMS \
    FOR_PROBLEM(3)         \
    FOR_PROBLEM(15)        \
    FOR_PROBLEM(16)        \
    FOR_PROBLEM(56)        \
    FOR_PROBLEM(66)        \
    FOR_PROBLEM(116)       \
    FOR_PROBLEM(172)       \
    FOR_PROBLEM(263)       \
    FOR_PROBLEM(264)       \
    FOR_PROBLEM(278)       \
    FOR_PROBLEM(297)       \
    FOR_PROBLEM(313)       \
    FOR_PROBLEM(371)       \
    FOR_PROBLEM(382)       \
    FOR_PROBLEM(509)       \
    FOR_PROBLEM(560)       \
    FOR_PROBLEM(709)       \
    FOR_PROBLEM(763)       \
    FOR_PROBLEM(819)       \
    FOR_PROBLEM(833)       \
    FOR_PROBLEM(836)       \
    FOR_PROBLEM(905)       \
    FOR_PROBLEM(941)       \
    FOR_PROBLEM(1010)      \
    FOR_PROBLEM(1146)      \
    FOR_PROBLEM(1275)      \
    FOR_PROBLEM(1344)      \
    FOR_PROBLEM(1352)      \
    FOR_PROBLEM(1544)      \
